doctrine:
    dbal:
        password: '%env(DATABASE_PASSWORD)%'
        dbname: chancellerie
        user: '%env(DATABASE_USERNAME)%'
        # if the url option is specified, it will override the above config
        url: postgresql://%env(DATABASE_USERNAME)%:%env(DATABASE_PASSWORD)%@127.0.0.1:5432/chancellerie?serverVersion=13&charset=utf8
        # the DBAL driverClass option
        # the DBAL driverOptions option


        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
