twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        IndiceCalculator: '@App\Service\IndiceCalculator'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
