twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        IndiceCalculator: '@App\Service\IndiceCalculator'
        AffectationGetter: '@App\Service\AffectationGetter'
        Encoder: '@App\Service\Encoder'
        SousDossierStringGetter: '@App\Service\SousDossierStringGetter'

when@test:
    twig:
        strict_variables: true
